# Generated by Django 5.0 on 2023-12-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalist',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
