# Generated by Django 5.0 on 2023-12-17 22:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_created_at_episodes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.upload_image),
        ),
    ]
