# Generated by Django 5.0 on 2023-12-17 22:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_episodes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalist',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.upload_image),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.upload_image),
        ),
    ]
