# Generated by Django 5.0 on 2023-12-17 23:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_finalist_image_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.SlugField(auto_created=models.CharField(max_length=300), max_length=300, unique=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('iconTypeRedeSocial', models.CharField(choices=[('insta', 'Instragram'), ('face', 'Facebook'), ('github', 'Github'), ('linkedln', 'Linkedln'), ('twitter', 'Twitter')], max_length=10)),
                ('linkRedeSocial', models.CharField(max_length=300)),
                ('imagem_capa', models.CharField(max_length=300)),
                ('resumo', models.CharField(max_length=500)),
                ('texto', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('aprovado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'permissions': (('check_approved', 'Check approved'),),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='finalist',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
