# Generated by Django 5.0 on 2023-12-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_alter_category_id_alter_episodes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='iconTypeRedeSocial',
            field=models.CharField(choices=[('insta', 'Instragram'), ('linkedln', 'Linkedln'), ('face', 'Facebook'), ('github', 'Github'), ('twitter', 'Twitter')], max_length=10),
        ),
    ]
