# Generated by Django 5.0 on 2023-12-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_icontyperedesocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='iconTypeRedeSocial',
            field=models.CharField(choices=[('linkedln', 'Linkedln'), ('twitter', 'Twitter'), ('insta', 'Instragram'), ('github', 'Github'), ('face', 'Facebook')], max_length=10),
        ),
    ]
